version: "3.3"

networks:
  app-network:

services:
  app:
    build: .
    ports:
      - "8080:8080"
    networks:
      - app-network
    environment:
      AUTORIZATION_SERVER_URL: "https://run.mocky.io/v3/5794d450-d2e2-4412-8131-73d0293ac1cc"
      NOTIFICATION_SERVER_URL: "https://run.mocky.io/v3/54dc2cf1-3add-45b5-b5a9-6bf7e7f1f4a6"
    depends_on:
      - kafka

  kafka:
    image: 'bitnami/kafka:latest'
    hostname: kafka
    ports:
      - '9094:9094'
    networks:
      - app-network
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,EXTERNAL://kafka:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER