version: "3.9"

services:
  app:
    build: .
    ports:
      - "8080:8080"
    networks:
      - app-network
    environment:
      RABBITMQ_HOST: "rabbitmq"
      RABBITMQ_PORT: 5672
      RABBITMQ_USERNAME: "guest"
      RABBITMQ_PASSWORD: "guest"
      AUTORIZATION_SERVER_URL: "https://run.mocky.io/v3/5794d450-d2e2-4412-8131-73d0293ac1cc"
      NOTIFICATION_SERVER_URL: "https://run.mocky.io/v3/54dc2cf1-3add-45b5-b5a9-6bf7e7f1f4a6"
    depends_on:
      - rabbitmq

  rabbitmq:
    image: rabbitmq:3-management-alpine
    hostname: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - app-network
    volumes:
      - ./rabbitmq-data:/var/lib/rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
      RABBITMQ_SERVER_PROPERTIES_OPTIONS='{"ha-mode": "none"}'
      RABBITMQ_DEFAULT_VHOST: "myvhost"
      RABBITMQ_PRECONFIGURED_VHOSTS: |
        {"myvhost": {
          "exchanges": [
            {"name": "pagamento-request-exchange", "type": "topic"}
          ],
          "queues": [
            {"name": "pagamento-request-queue", "durable": true, "arguments": {"x-ha-queues": 1}}
          ],
          "bindings": [
            {"source": "myexchange", "destination": "myqueue", "routing_key": "pagamento-request-rout-key"}
          ]
        }}